# docker-compose build --progress=plain mpbuilder

services:
  mpbuilder:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: .
      args:
         ##### Settings #####

         # Please make sure you use .TAR.XZ archive
         idf_version_tag: 'v4.3.1'
         micropython_version_tag: 'v1.18'
         idf_build_platforms: 'esp32, esp32s2'
         idf_target:  'esp32s2'
    environment:
      idf_version_tag: 'v4.3.1'
      micropython_version_tag: 'v1.18'
      idf_build_platforms: 'esp32, esp32s2'
      port_to_build: 'esp32'
      idf_target: 'esp32'
      MICROPY_BOARD: 'ESP32_TTGO_T_DISPLAY'
    volumes:
      - .:/build
    platform: linux/amd64
